import { DocumentDownloadIcon } from "@heroicons/react/solid";

export const news = [
    {
      id: 1,
      content: "agroform - Marktreport",
      target: <nobr>Hot News</nobr>,
      href: "#",
      date: "KW07",
      icon: DocumentDownloadIcon,
      iconBackground: "bg-green-lighter",
    },
    {
      id: 2,
      content: "Advanced to phone screening by",
      target: "Bethany Blake",
      href: "#",
      date: "Sep 22",
      datetime: "2020-09-22",
      icon: DocumentDownloadIcon,
      iconBackground: "bg-blue-500",
    },
    {
      id: 3,
      content: "Completed phone screening with",
      target: "Martha Gardner",
      href: "#",
      date: "KW07",
      datetime: "2020-09-28",
      icon: DocumentDownloadIcon,
      iconBackground: "bg-green-500",
    },
    {
      id: 4,
      content: "Advanced to interview by",
      target: "Bethany Blake",
      href: "#",
      date: "Sep 30",
      datetime: "2020-09-30",
      icon: DocumentDownloadIcon,
      iconBackground: "bg-blue-500",
    },
    {
      id: 5,
      content: "Completed interview with",
      target: "Katherine Snyder",
      href: "#",
      date: "Oct 4",
      datetime: "2020-10-04",
      icon: DocumentDownloadIcon,
      iconBackground: "bg-green-500",
    },
  ];