import iconValentia from "../../image/svg/ICON_fg_valentia.svg";
import iconCrozier from "../../image/svg/ICON_fg_crozier.svg";
import iconBoltXl from "../../image/svg/ICON_fg_boltXl.svg";
import iconHurler from "../../image/svg/ICON_fg_hurler.svg";

export const productData = [
    {
      name: "Valentia",
      ingredient1: "100g/l Fluroxypyr +",
      ingredient2: "2g/l Florasulam",
      role: "Admin",
      slogan: "Einzigartig in Mais – Top in Getreide",
      field1: "Corn",
      feld1: "Mais",
      styling1: "text-white bg-green-light",
      field2: "Cereals",
      feld2: "Getreide",
      styling2: "text-white bg-yellow-light",
      link: "./agroform/valentia",
      image: iconValentia,
      cat:"Cereals"
    },
    {
      name: "Crozier",
      ingredient1: "800g/l Prosulfocarb",
      ingredient2: "",
      slogan: "Doppeltes Potential für Ihr Feld",
      field1: "Potato",
      feld1: "Kartoffeln",
      styling1: "text-white bg-brown-medium",
      field2: "Cereals",
      feld2: "Getreide",
      styling2: "text-white bg-yellow-light",
      link: "./agroform/crozier",
      image: iconCrozier,
    },
    {
      name: "BoltXL",
      ingredient1: "250 g/l Prothioconazol",
      ingredient2: "",
      slogan: "Die leistungsstarke Azol-Formulierung",
      field1: "Rape",
      feld1: "Raps",
      styling1: "text-white bg-yellow-lighter",
      field2: "Cereals",
      feld2: "Getreide",
      styling2: "text-white bg-yellow-light",
      link: "./agroform/crozier",
      image: iconBoltXl,
    },
    {
      name: "Hurler",
      ingredient1: "200 g/l Fluroxypyr",
      ingredient2: "",
      slogan: "Gegen Unkräuter von früh bis spät",
      field1: "Cereals",
      feld1: "Getreide",
      styling1: "text-white bg-yellow-light",
      field2: "Corn",
      feld2: "Mais",
      styling2: "text-white bg-green-light",
      link: "./agroform/crozier",
      image: iconHurler,
    },
  ];